' Gambas module file

Public block_drive As String = "Finfosys.ComboBox4.Text"
Public device_model As String
Public device_vendor As String
Public mount_point As String
Public device_uuid As String
Public real_size As String
Public filesystem_type As String
Public mount_widtch As String
Public device_rev As String
Public max_sectors As String
Public device_state As String
Public modalias As String
Public Used As String
Public check_swap As String
Public removable As String
Public ext_range As String
Public range As String
Public add_random As String
Public discard_granularity As String
Public discard_max_bytes As String
Public discard_zeroes_data As String
Public hw_sector_size As String
Public max_hw_sectors_kb As String
Public max_sectors_kb As String
Public max_segments As String
Public max_segment_size As String
Public read_ahead_kb As String
Public scheduler As String

Public Sub _inits()
  Dim sdx As String
  Dim Avail_HDD As Integer 
  Dim Max_HDD As Integer
  Dim cache As String
  Debug "Add Drives to ComboBox"
  Shell "ls /sys/block/ | grep -e 'sd' -e 'sr' | tr ' ' '\n' | wc -l" Wait To cache
  Max_HDD = Val(cache)
  For Avail_HDD = 1 To Max_HDD
   Shell "ls /sys/block/ | grep -e 'sd' -e 'sr' | tr ' ' '\n' | sed -n '" & Avail_HDD & "p'" Wait To sdx
   sdx = Replace(sdx, "\n", "")
   Finfosys.ComboBox4.Add(sdx)
  Next
End

Public Sub _init_2()
 
  Dim ListAllDiscs, risultato As String
  Dim righe As New String[]
  Dim count As Integer
  Dim riga As New String[]
  Dim lista As New String[]
  Debug "Add Drives to ComboBox.."
  Shell "ls /sys/block/" & Finfosys.ComboBox4.Text & " | grep 'sd'" To ListAllDiscs
  righe = Split(ListAllDiscs, "\n", "%%", True)
  For count = 0 To righe.Max
  riga = Split(righe[count], " ", "%%", True)
  risultato = Replace(riga[0], " ", "")
  lista.add(risultato)
  Next
  Finfosys.ComboBox3.List = lista
  Finfosys.ComboBox3.Index = 0
End

Public Sub get_informations()
  Debug "Get informations of Drives"
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/device/model" Wait To device_model
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/device/vendor" Wait To device_vendor
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/device/rev" Wait To device_rev
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/device/max_sectors" Wait To max_sectors
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/device/state" Wait To device_state
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/device/modalias" Wait To modalias
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/removable" Wait To removable
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/ext_range" Wait To ext_range
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/range" Wait To range
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/add_random" Wait To add_random
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/discard_granularity" Wait To discard_granularity
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/discard_max_bytes" Wait To discard_max_bytes
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/discard_zeroes_data" Wait To discard_zeroes_data
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/hw_sector_size" Wait To hw_sector_size
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/max_hw_sectors_kb" Wait To max_hw_sectors_kb
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/max_sectors_kb" Wait To max_sectors_kb
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/max_segments" Wait To max_segments
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/max_segment_size" Wait To max_segment_size
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/read_ahead_kb" Wait To read_ahead_kb
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/queue/scheduler" Wait To scheduler
  Shell "cat /sys/block/" & Finfosys.ComboBox4.Text & "/" & Finfosys.ComboBox3.Text & "/size" Wait To real_size
  Shell "" & ChkPrm.ChkExecDir("swapon") & " -s | sed -n '2p' | awk {'print $1'} | cut -d '/' -f 3" Wait To check_swap
  Shell "df | grep '" & Finfosys.ComboBox3.Text & "' | awk {'print $5'} | sed -n '1p'" Wait To used
  Debug "Get informations of Drives Done" 
  Debug "Replace new line to Null"
  rm_new_line()
  disks()
End

Public Sub rm_new_line()
 
  device_model = Replace(device_model, "\n", "")
  device_vendor = Replace(device_vendor, "\n", "")
  device_uuid = Replace(device_uuid, "\n", "")
  real_size = ((Replace(real_size, "\n", "") / 1024000) / 2) & " GB"
  filesystem_type = Replace(filesystem_type, "\n", "")
  mount_widtch = Replace(mount_widtch, "\n", "")
  device_rev = Replace(device_rev, "\n", "")
  max_sectors = Replace(max_sectors, "\n", "")
  device_state = Replace(device_state, "\n", "")
  modalias = Replace(modalias, "\n", "")
  Used = Replace(Used, "\n", "")
  Used = Replace(Used, "%", "")
  check_swap = Replace(Replace(check_swap, "", ""), "\n", "")
  removable = Replace(removable, "\n", "")
  ext_range = Replace(ext_range, "\n", "")
  range = Replace(range, "\n", "")
  add_random = Replace(add_random, "\n", "")
  discard_granularity = Replace(discard_granularity, "\n", "")
  discard_max_bytes = Replace(discard_max_bytes, "\n", "")
  discard_zeroes_data = Replace(discard_zeroes_data, "\n", "")
  hw_sector_size = Replace(hw_sector_size, "\n", "")
  max_hw_sectors_kb = Replace(max_hw_sectors_kb, "\n", "")
  max_sectors_kb = Replace(max_sectors_kb, "\n", "")
  max_segments = Replace(max_segments, "\n", "")
  max_segment_size = Replace(max_segment_size, "\n", "")
  read_ahead_kb = Replace(read_ahead_kb, "\n", "")
  scheduler = Replace(scheduler, "\n", "")
  Debug "Replace new line to Null Done"
 
End

Public Sub disks()
  Shell "grep '" & Finfosys.ComboBox3.Text & "' /proc/mounts | awk {'print $4'}" Wait To mount_widtch
  Shell "LC_ALL=C df | grep '" & Finfosys.ComboBox3.Text & "' | awk {'print $6, $7'} | sed -n '1p'" Wait To mount_point
  Shell "ls -l /dev/disk/by-uuid/ | grep " & Finfosys.ComboBox3.Text & " | awk {'print $9'}" Wait To device_uuid
  device_uuid = Replace(Replace(device_uuid, " ", ""), "\n", "")
  Shell "grep '" & Finfosys.ComboBox3.Text & "' /proc/mounts | awk {'print $3'}" Wait To filesystem_type
  filesystem_type = Replace(Replace(filesystem_type, " ", ""), "\n", "")
  If mount_widtch = Null Then
  Shell "grep '" & device_uuid & "' /proc/mounts | awk {'print $4'}" Wait To mount_widtch
  Endif
  mount_widtch = Replace(mount_widtch, "\n", "")
  If filesystem_type = Null Then
  Shell "grep '" & device_uuid & "' /proc/mounts | awk {'print $3'}" Wait To filesystem_type
  Endif
  filesystem_type = Replace(Replace(filesystem_type, " ", ""), "\n", "")
  If device_uuid = Null Then
  filesystem_type = Null
  Endif
  If mount_point Like "*Mounted on*" Then 
  Shell "LC_ALL=C df | grep '" & Finfosys.ComboBox4.Text & "' | awk {'print $6, $7'} | sed -n '1p'" Wait To mount_point
  Endif
  mount_point = Replace(mount_point, "\n", "")
End
