' Gambas module file

Public Sub _init()

 If Exist("~/.i-nex/report-ng.sh") Then
  Shell "rm ~/.i-nex/report-ng.sh" Wait
 Endif
 If Exist("~/.i-nex") Then
  Print "i-nex in home folder is exist"
 Else
  Shell "mkdir -p ~/.i-nex/" Wait
 Endif
 Copy "Data/report-ng.sh" To User.Home &/ ".i-nex/report-ng.sh"
 Shell "/bin/bash " & User.Home &/ ".i-nex/report-ng.sh" Wait
 
 'echo "[System] \
'DistributionVendor = $vendor \
'DistributionRelease = $release " > ~/.i-nex/dist.conf"
End

