' Gambas module file

' Copyright(C) 2011-2014, Michał Głowienka aka eloaders <eloaders@linux.pl>
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program. If not, see <http://www.gnu.org/licenses/>.

' 
Public Sub _init()
 
 Dim central_processor_unit As String = Finfosys.cpu
 central_processor_unit = Replace(Replace(Replace(central_processor_unit, "(", ""), "(", ""), "\n", "")
 central_processor_unit = Replace(Replace(central_processor_unit, "TM", ""), "R", "")
 
End
