' Gambas module file

' Copyright(C) 2011-2014, Michał Głowienka aka eloaders <eloaders@linux.pl>
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program. If not, see <http://www.gnu.org/licenses/>.

Public Logs As New Logger
Public i As Integer
Public database As Collection
Public Sub _inits()
  Dim buffer, cpucache As String
  Dim z As Integer
  Select Case Finfosys.Label14.Text
   Case Like "*Opteron*"
    Logs("Use AMD Opteron CPU Database", Logger.Info)
    buffer = File.Load("Database/Opteron")
   Case Like "*amd*"
    Logs("Use AMD CPU Database", Logger.Info)
    buffer = File.Load("Database/amd")
   Case Like "*Xeon*"
    Logs("Use Intel Xeon CPU Database", Logger.Info)
    buffer = File.Load("Database/Xeon")
   Case Like "*atom*"
    Logs("Use Intel Atom CPU Database", Logger.Info)
    buffer = File.Load("Database/atom")
   Case Like "*intel*"
    Logs("Use Intel CPU Database", Logger.Info)
    buffer = File.Load("Database/intel")
  End Select
  Logs("Decode CPU Database", Logger.Info)
  database = JSON.Decode(buffer)
  cpucache = Finfosys.Label14.Text
  Logs("Replace CPU Strings to Null", Logger.Info)
  
  cpucache = Replace(Replace(Replace(Replace(cpucache, "with", "*"), "APU", "*"), "Graphics", "*"), "Radeon", "*")
  cpucache = Replace(Replace(Replace(Replace(Replace(Replace(Replace(cpucache, "Intel", ""), " ", "*"), "R", ""), "CPU", ""), "TM", ""), ")", ""), "(", "")
  cpucache = Replace(Replace(Replace(Replace(Replace(cpucache, "AMD", "*"), "Core", "*"), "Dual", "*"), "Processor", "*"), "tm", "*")
  cpucache = Replace(Replace(Replace(cpucache, "HD", "*"), "-", "*"), "Eight", "*")
  cpucache = Replace(Replace(Replace(cpucache, "Triple", ""), "Six", ""), "Quad", "")
  For z = 0 To database["DATABASE"].Count - 1
    If database["DATABASE"][z]["PROCESSOR_MODEL_NAME"] Like "*" & cpucache & "*" Then 

      Finfosys.PictureBox3.Picture = Picture["Database/Logos/" & database["DATABASE"][z]["PROCESSOR_SOCKET_IMAGE"] & ""]
      'Finfosys.PictureBox3.Picture = Picture["Database/Logos/306.gif"]
      Finfosys.Label103.Text = " Integrated GPU: " & database["DATABASE"][z]["PROCESSOR_INTEGRATEDGRAPHIC"]
      Finfosys.Label104.Text = " TDP: " & database["DATABASE"][z]["PROCESSOR_TDP"]
      Finfosys.Label110.Text = " PPS: " & database["DATABASE"][z]["PROCESSOR_PROCESS_SIZE"]
      Finfosys.Label111.Text = " Socket: " & database["DATABASE"][z]["PROCESSOR_SOCKET"]
      Finfosys.Label112.Text = " Transistors: " & database["DATABASE"][z]["PROCESSOR_TRANSISTORS"]
      Finfosys.Label113.Text = " Die size: " & database["DATABASE"][z]["PROCESSOR_DIE_SIZE"]
      Finfosys.Label114.Text = " Package: " & database["DATABASE"][z]["PROCESSOR_PACKAGE"]
      Finfosys.Label115.Text = " Tcasemax: " & database["DATABASE"][z]["PROCESSOR_TCASEMAX"]
      Finfosys.Label116.Text = " Turboclock: " & database["DATABASE"][z]["PROCESSOR_TURBOCLOCK"] 
      Finfosys.Label117.Text = " Multiplier: " & database["DATABASE"][z]["PROCESSOR_MULTIPLIER"]
      Finfosys.Label118.Text = " Voltage: " & database["DATABASE"][z]["PROCESSOR_VOLTAGE"]
      Finfosys.Label119.Text = " Codename: " & database["DATABASE"][z]["PROCESSOR_CODENAME"]
      Finfosys.Label120.Text = " Part: " & database["DATABASE"][z]["PROCESSOR_PART"]
      Finfosys.Label121.Text = " Memory support: " & database["DATABASE"][z]["PROCESSOR_MEMORYSUPPORT"]
      i = z
      Break
    Endif
  Next
  Logs("Current position of processor = " & cpucache & " is = " & z & "", Logger.Info)
End
