' Gambas module file

Public Temperature As String
Public calculate As Float
Public OK As Boolean
Public notsupporttemp As Float

Public Sub _inits()
 
 If Exist("/sys/bus/acpi/devices/LNXTHERM:00/thermal_zone/") Then
 Shell "cat /sys/bus/acpi/devices/LNXTHERM:00/thermal_zone/temp" Wait To Temperature
 If Temperature = Null Then
  notsupporttemp = 1
 Else
  notsupporttemp = 0
  calculate = CFloat(Val(Temperature))
 Endif
 Endif
 
 If Exist("/sys/class/hwmon/hwmon0/device/temp2_input") Then
 Shell "cat /sys/class/hwmon/hwmon0/device/temp2_input" Wait To Temperature
 If Temperature = Null Then
  notsupporttemp = 1
 Else
  notsupporttemp = 0
  calculate = CFloat(Val(Temperature))
 Endif
 Endif
 'calculate = Replace(Replace(Temperature, " ", ""), "\n", "")
 
 
End
