' Gambas module file

Public Logs As New Logger
Public Product As String
Public bMaxPower As String
Public manufacturer As String
Public speed As String
Public Version As String
Public idProduct As String
Public idVendor As String
Public Serial As String
Public lsusb As String
Public ListAllDiscs As String

Public Sub _inits()
  Dim risultato As String
  Dim righe As New String[]
  Dim count As Integer
  Dim riga As New String[]
  Dim lista As New String[]
  Logs("Add Drives to ComboBox..", Logger.Info)
  Shell "ls /sys/bus/usb/devices/*/* | grep 'manufacturer' | grep usb | cut -d '/' -f 6" To ListAllDiscs
  righe = Split(ListAllDiscs, "\n", "%%", True)
  For count = 0 To righe.Max
  riga = Split(righe[count], " ", "%%", True)
  risultato = Replace(riga[0], " ", "")
  lista.add(risultato)
  Next
  Finfosys.ComboBox5.List = lista
  Finfosys.ComboBox5.Index = 0
 
End

Public Sub get_informations()
 'Product = File.Load("/sys/bus/usb/devices/usb1/product")
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/product" Wait To Product
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/bMaxPower" Wait To bMaxPower
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/manufacturer" Wait To manufacturer
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/speed" Wait To speed
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/version" Wait To Version
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/idProduct" Wait To idProduct
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/idVendor" Wait To idVendor
 Shell "cat /sys/bus/usb/devices/" & Finfosys.ComboBox5.Text & "/serial" Wait To Serial
 Shell "lsusb -d " & idVendor & ":" & idProduct & "" Wait To lsusb
 export_informations()
End

Public Sub export_informations()
 Product = Replace(Product, "\n", "")
 bMaxPower = Replace(bMaxPower, "\n", "")
 manufacturer = Replace(manufacturer, "\n", "")
 speed = Replace(speed, "\n", "")
 Version = Replace(Version, "\n", "")
 idProduct = Replace(idProduct, "\n", "")
 idVendor = Replace(idVendor, "\n", "")
 Shell "lsusb -d " & idVendor & ":" & idProduct & "" Wait To lsusb
 lsusb = Replace(lsusb, "\n", "")
 Serial = Replace(Serial, "\n", "")
 Finfosys.TextBox40.Text = Product
 Finfosys.TextBox41.Text = bMaxPower
 Finfosys.TextBox42.Text = manufacturer
 Finfosys.TextBox46.Text = speed & " MB"
 Finfosys.TextBox49.Text = Version
 Finfosys.TextBox50.Text = idProduct
 Finfosys.TextBox51.Text = idVendor
 Finfosys.TextBox43.Text = lsusb
 Finfosys.TextBox54.Text = Serial
End
