#!/bin/bash

DATE=$(date -R)
GIT_RV=$(git rev-list HEAD | wc -l)
INEX_VERSION=$(grep "Version=" src/i-nex/.project | cut -d "=" -f 2)
DATE_Y_M_D=$(date +%Y%m%d)

echo "i-nex ($INEX_VERSION-0~git$GIT_RV~$DATE_Y_M_D) unstable; urgency=low

  * next unstable

 -- eloaders <eloaders@yahoo.com>  $DATE
" >debian/changelog1
 
cp debian/changelog debian/changelog_bak
cat debian/changelog >> debian/changelog1
mv debian/changelog1 >> debian/changelog
dpkg-buildpackage
mv debian/changelog_bak debian/changelog