#!/bin/bash
bindir="/usr/bin/"
	mkdir -p $bindir
	mkdir -p /usr/lib/gambas3/
	mkdir -p /usr/share/pixmaps/
	mkdir -p /usr/share/applications/
	mkdir -p /usr/share/doc/i-nex/
	mkdir -p /usr/share/i-nex/pastebinit/
	mkdir -p /usr/share/i-nex/pastebinit/pastebin.d/
	install -m 0755 usr/bin/i-nex $bindir
	install -m 0755 usr/bin/inex-edid $bindir
	install -m 0755 usr/bin/i-nex.gambas $bindir
	install -m 0755 usr/share/pixmaps/i-nex.0.4.x.png /usr/share/pixmaps/
	install -m 0755 usr/share/applications/i-nex.desktop /usr/share/applications/
	install -m 0755 usr/bin/check_kernel /usr/bin/
	install -m 0755 usr/bin/i-nex-lspci /usr/bin/
	install -m 0755 usr/share/doc/i-nex/I-Nex.LICENSE /usr/share/doc/i-nex/
	install -m 0755 usr/share/i-nex/pastebinit/Pastebinit.LICENSE /usr/share/i-nex/pastebinit/
	install -m 0755 usr/share/i-nex/pastebinit/pastebin.d/* /usr/share/i-nex/pastebinit/pastebin.d/
	install -m 0755 usr/share/i-nex/pastebinit/pastebinit /usr/share/i-nex/pastebinit/
	install -m 0755 usr/share/i-nex/pastebinit/pastebinit.xml /usr/share/i-nex/pastebinit/
	install -m 0755 usr/share/i-nex/pastebinit/README /usr/share/i-nex/pastebinit/
	install -m 0755 usr/share/i-nex/pastebinit/release.conf /usr/share/i-nex/pastebinit/
	install -m 0775 usr/bin/gbx3 /usr/bin/gbx3
	install -m 0775 usr/bin/gbr3 /usr/bin/gbr3
	install -m 0775 usr/lib/gambas3/gb.debug.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.desktop.gambas /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.desktop.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.draw.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.eval.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.form.gambas /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.form.stock.gambas /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.geom.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.gtk.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.gui.base.gambas /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.gui.opengl.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.gui.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.image.so /usr/lib/gambas3/
	install -m 0775 usr/lib/gambas3/gb.qt4.so /usr/lib/gambas3/