.TH "pastebinit" 1
.SH NAME
pastebinit \- a command line Pastebin client
.SH USAGE
.B pastebinit
pastebinit [-ibaftup]
.SH DESCRIPTION
.TP
This software reads text and send it to a Pastebin on the internet, finally it gives the URL back to the user.
.PP
It allows the text to be passed through a pipe (|) or from a file passed as a parameter.
.SH OPTIONS
.RS
.RE
.B Required arguments:
.RE
-i <filename> (can be replaced by piped datas)
.RE
.B Optional arguments:
.RE
-b <pastebin url>
.RE
-a <author>
.RE
-f <format of paste>
.RE
.B Optional arguments supported only by lt2.us:
.RE
-t <title of paste>
.RE
-u <username>
.RE
-p <password>
.RE
.SH SUPPORTED PASTEBINS
.RS
.RE
http://paste.stgraber.org
.RE
http://*.pastebin.com
.RE
http://pastebin.ca
.RE
http://*.1t2.us
.SH BUGS
.RS
.RE
If you have found a bug or if you want another Pastebin to be added, please send a bug report on :
.RE
https://bugs.launchpad.net/products/pastebinit/+bugs
.SH AUTHORS
.RS
.RE
Pastebinit is currently written by Stephane Graber.
.RE
lt2.us, username, password, format, title, arguments and redirect support added by Daniel Bartlett.
.RE
Website : http://www.stgraber.org/category/pastebinit
.RE
E-Mail : stgraber@stgraber.org
