' Gambas module file

' Gambas module file

Library "libcpuid:14"

Public Struct cpu_id_t
  vendor_str As String
  brand_str As String
  vendor As Integer
  family As Integer
  model As Integer
  stepping As Integer
  ext_family As Integer
  ext_model As Integer
  num_cores As Integer
  num_logical_cpus As Integer
  total_logical_cpus As Integer
  l1_data_cache As Integer
  l1_instruction_cache As Integer
  l2_cache As Long 
  l3_cache As Long
  l4_cache As Long
  l1_assoc As Long
  l2_assoc As Long
  l3_assoc As Long
  l4_assoc As Long
  l1_cacheline As Long
	l2_cacheline As Long
	l3_cacheline As Long
  l4_cacheline As Long
  cpu_codename As String
  sse_size As Integer
  detection_hints As Integer
End Struct

Public Struct cpu_mark_t
 tsc As Long
 sys_clock As Long
End Struct
' int sysinfo (struct sysinfo *__info)
' Returns information on overall system statistics.
Private Extern cpuid_get_total_cpus() As Integer
Private Extern cpu_mark_t() As Integer
Private Extern cpu_id_t() As Integer
Public Logs As New Logger

Public Sub Main()
 
 Dim si As New Cpu_id_t
 Dim err As Integer
   
  ' err = cpu_id_t(si)
  ' If err < 0 Then
  '  Logs("Libcpuid cpu_id_t Error", Logger.Error)
  ' Elsepu_exec_cpuid()
   Print cpuid_get_total_cpus()
   Print si.brand_str
   Print si.cpu_codename
   Print si.detection_hints
   Print si.ext_family
   Print si.ext_model
   Print si.family
   Print si.l1_assoc
   Print si.l1_cacheline
   Print si.l1_data_cache
   Print si.l1_instruction_cache
   Print si.l2_assoc
   Print si.l2_cache
  'Endif
End
