#!/usr/bin/make -f
INSTALL = install -m
install:
	$(INSTALL) 0755 changelog-0.4.6 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.4.8 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.4.8.1 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.5.0 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.5.1 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.5.2 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.5.4 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.5.6 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.5.8 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.6.0 $(DESTDIR)/usr/share/doc/i-nex/
	$(INSTALL) 0755 changelog-0.6.2 $(DESTDIR)/usr/share/doc/i-nex/