' Gambas module file

Public Sub _inits()
 Dim i As Integer
 Dim hFile As File
 If Exist(FReport_Gen.ButtonBox1.Text) Then  
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Append 
 Else 
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Create
 Endif 
 Write #hFile, "==========================================================CPUID==================================================================="
 Write #hFile, Finfosys.DATAT["VENDOR_STR"]
 Write #hFile, Finfosys.DATAT["CPU_CODENAME"]
 Write #hFile, Finfosys.DATAT["BRAND_STR"]
 Write #hFile, "Cores:  " & Finfosys.DATAT["NUM_CORES"] & ""
 Write #hFile, "Logical CPUS:  " & Finfosys.DATAT["NUM_LOGICAL_CPUS"] & ""
 Write #hFile, "Total Logical CPUS:  " & Finfosys.DATAT["TOTAL_LOGICAL_CPUS"] & ""
 Write #hFile, "Family:  " & Finfosys.DATAT["FAMILY"] & ""
 Write #hFile, "Model:  " & Finfosys.DATAT["MODEL"] & ""
 Write #hFile, "Stepping:  " & Finfosys.DATAT["STEPPING"] & ""
 Write #hFile, "Ext Family:  " & Finfosys.DATAT["EXT_FAMILY"] & ""
 Write #hFile, "Ext Model:  " & Finfosys.DATAT["EXT_MODEL"] & ""
 Write #hFile, "CPU Clock:  " & Finfosys.DATAT["CPU_CLOCK"] & ""
 Write #hFile, "CPU Clock BY OS:  " & Finfosys.DATAT["CPU_CLOCK_BY_OS"] & ""
 Write #hFile, "CPU Clock BY IC:  " & Finfosys.DATAT["CPU_CLOCK_BY_IC"] & ""
 Write #hFile, "CPU Clock Measure:  " & Finfosys.DATAT["CPU_CLOCK_MEASURE"] & ""
 Write #hFile, "Mark TSC:  " & Finfosys.DATAT["MARK_TSC"] & ""
 Write #hFile, "Mark SYS Clock:  " & Finfosys.DATAT["MARK_SYS_CLOCK"] & ""
 Write #hFile, "L1 Data:  " & Finfosys.DATAT["L1_DATA_CACHE"] & ""
 Write #hFile, "L1 Instr:  " & Finfosys.DATAT["L1_INSTRUCTION_CACHE"] & ""
 Write #hFile, "L2 Cache:  " & Finfosys.DATAT["L2_CACHE"] & ""
 Write #hFile, "L3 Cache:  " & Finfosys.DATAT["L3_CACHE"] & ""
 Write #hFile, "L1 Assoc:  " & Finfosys.DATAT["L1_ASSOC"] & ""
 Write #hFile, "L2 Assoc:  " & Finfosys.DATAT["L2_ASSOC"] & ""
 Write #hFile, "L3 Assoc:  " & Finfosys.DATAT["L3_ASSOC"] & ""
 Write #hFile, "L1 Cacheline:  " & Finfosys.DATAT["L1_CACHELINE"] & ""
 Write #hFile, "L2 Cacheline:  " & Finfosys.DATAT["L2_CACHELINE"] & ""
 Write #hFile, "L3 Cacheline:  " & Finfosys.DATAT["L3_CACHELINE"] & ""
 Write #hFile, "SSE Size:  " & Finfosys.DATAT["SSE_SIZE"] & ""
 Write #hFile, "==========================================================FLAGS==================================================================="
 For i = 1 To 94
  FReport_Gen.ProgressBar1.Value = i / 94
  Try Write #hFile, Finfosys.DATAT["Flags"][i]["DESC"] & " | " & Finfosys.DATAT["Flags"][i]["FEATURE"] & " | " & get_value(0, i)
 Next
 Close #hFile 
End

Function get_value(Value As Integer, Pos As Integer) As String
 
 If Finfosys.DATAT["Flags"][Pos]["VALUE"] = 1 Then
  Return "Is Supported"
 Else
  Return "Not Supported"
 Endif
 
End

