' Gambas module file

Public Sub _lspci()
_ohce("LSPCI")
Shell "lspci >>" & FReport_Gen.ButtonBox1.Text & "" Wait
FReport_Gen.ProgressBar1.Value = 1 / 12
Wait 0.01
End

Public Sub _lsusb()
_ohce("LSUSB")
Shell "lsusb >>" & FReport_Gen.ButtonBox1.Text & "" Wait
FReport_Gen.ProgressBar1.Value = 2 / 12
Wait 0.01
End

Public Sub _scsi()
_ohce("SCSI")
Shell "cat /proc/scsi/scsi >>" & FReport_Gen.ButtonBox1.Text & "" Wait
FReport_Gen.ProgressBar1.Value = 3 / 12
Wait 0.01
End

Public Sub _mtrr()
_ohce("PROC MTRR")
Shell "cat /proc/mtrr >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 5 / 12
 Wait 0.01
End

Public Sub _devices()
_ohce("PROC DEVICES")
Shell "cat /proc/devices >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 6 / 12
 Wait 0.01
End

Public Sub _diskstats()
_ohce("PROC DISKSTATS")
Shell "cat /proc/diskstats >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 7 / 12
 Wait 0.01
End

Public Sub _dma()
_ohce("PROC DMA")
Shell "cat /proc/dma >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 8 / 12
 Wait 0.01
End

Public Sub _partitions()
_ohce("PROC PARTITIONS")
Shell "cat /proc/partitions >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 9 / 12
 Wait 0.01
End

Public Sub _modules()
_ohce("PROC modules")
Shell "cat /proc/modules >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 10 / 12
 Wait 0.01
End

Public Sub _cmdline()
_ohce("PROC cmdline")
Shell "cat /proc/cmdline >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 11 / 12
 Wait 0.01
End

Public Sub _grub()
_ohce("PROC GRUB")
Shell "cat /etc/default/grub >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 12 / 12
 Wait 0.01
End

Public Sub _dmesg()
_ohce("DMESG")
Shell "dmesg >>" & FReport_Gen.ButtonBox1.Text & "" Wait
 FReport_Gen.ProgressBar1.Value = 4 / 9
 Wait 0.01
End

Public Sub _cpuinfo()
 Dim hFile As File
 _ohce("CPUINFO")
 FReport_Gen.ProgressBar1.Value = 4 / 9
 If Exist(FReport_Gen.ButtonBox1.Text) Then  
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Append 
 Else 
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Create
 Endif 
 Write #hFile, File.Load("/proc/cpuinfo")
 Close #hFile
 Wait 0.01
End

Public Sub _ohce(txet As String)
 Dim hFile As File
 If Exist(FReport_Gen.ButtonBox1.Text) Then  
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Append 
 Else 
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Create
 Endif 
 Print #hFile, "========================================================" & txet & "================================================================="
 Close #hFile
End
