' Gambas module file

Public Sub _inits()
Dim hFile As File
 FReport_Gen.ProgressBar1.Value = 0
 If Exist(FReport_Gen.ButtonBox1.Text) Then  
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Append 
 Else 
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Create
 Endif
 FReport_Gen.ProgressBar1.Value = 50
 Write #hFile, "=========================================================================================================================" & "\n"
 Write #hFile, "___________________Board___________________" & "\n"
 Write #hFile, Finfosys.TextBox2.Text & "\n"
 Write #hFile, Finfosys.TextBox3.Text & "\n"
 Write #hFile, Finfosys.TextBox4.Text & "\n"
 Write #hFile, Finfosys.TextBox5.Text & "\n"
 Write #hFile, "___________________Bios____________________" & "\n"
 Write #hFile, Finfosys.TextBox6.Text & "\n"
 Write #hFile, Finfosys.TextBox21.Text & "\n"
 Write #hFile, Finfosys.TextBox22.Text & "\n"
 Write #hFile, "_________________Chassis__________________" & "\n"
 Write #hFile, Finfosys.TextBox23.Text & "\n"
 Write #hFile, Finfosys.TextBox24.Text & "\n"
 Write #hFile, Finfosys.TextBox25.Text & "\n"
 Write #hFile, Finfosys.TextBox26.Text & "\n"
 Write #hFile, "_________________Product__________________" & "\n"
 Write #hFile, Finfosys.TextBox27.Text & "\n"
 Write #hFile, Finfosys.TextBox28.Text & "\n"
 FReport_Gen.ProgressBar1.Value = 70
 Close #hFile
 FReport_Gen.ProgressBar1.Value = 100
End
