' Gambas module file

Public DATA_RETURN As String
Public Report As Collection = [("0"): ("===============================================" & Finfosys.ComboBox6.Text & "==================================================="),
                               ("1"): (Finfosys.Label73.Text),
                               ("2"): (Finfosys.Label78.Text),
                               ("3"): (Finfosys.Label9.Text),
                               ("4"): (Finfosys.TextArea18.Text)]
Public Sub _inits()
 Dim All, All2 As Integer
 Dim hFile As File
 DATA_RETURN = Null
 For All = 0 To Finfosys.ComboBox6.Count - 1
 FReport_Gen.ProgressBar1.Value = All / Finfosys.ComboBox6.Count - 1
  For All2 = 0 To Report.Count - 1
   FReport_Gen.ProgressBar1.Value = All2 / Report.Count - 1
   DATA_RETURN = DATA_RETURN & "\n" & Report[All2]
  Next
 Next
 If Exist(FReport_Gen.ButtonBox1.Text) Then  
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Append 
 Else 
    hFile = Open FReport_Gen.ButtonBox1.Text For Write Create
 Endif 
 Print #hFile, DATA_RETURN
 Close #hFile
End
