' Gambas module file

Public aScan As String[]
Public sLine As String
Public SCREENFETCH As Collection
Public Sub System()
  Dim default_display_manager As Boolean = Exist("/etc/X11/default-display-manager")
  Dim hostname, arch, gcc, timezone, xorg_version, glx_version As String
  Dim SCREENFETCH_P As Process
  SCREENFETCH_P = Exec ["" & ChkPrm.ChkExecDir("bash") & ""] For Write
  Write #SCREENFETCH_P, File.Load("Data/screenfetch-dev")
  SCREENFETCH_P.Wait
  SCREENFETCH = JSON.Decode(File.Load(User.Home & "/.i-nex/screenfetch.json"))
  
  Shell "cat /etc/timezone | grep ^TIMEZONE= /etc/sysconfig/clock | cut -d '=' -f 2" Wait To timezone
  If timezone = Null Or "" Then
    Shell "timedatectl status | grep \"Time zone:\" | cut -d \":\" -f 2 | cut -d \"(\" -f 1" Wait To timezone
  Endif
  'Detect heap size
  For Each sLine In Split(File.Load("/proc/self/maps"), "\n")
      If InStr(sLine, "[heap]") Then
        aScan = Scan(sLine, "*-* *")
        Finfosys.Label176.Text = "Heap size is " & Format(Val("&H" & aScan[1] & "&") - Val("&H" & aScan[0] & "&"), "#,##0") & " bytes."
        Break
      Endif
  Next
  'End od detect heap size
  hostname = System.Host
  arch = System.Architecture
  Shell "gcc -dumpversion" Wait To gcc
  Shell "cat /var/log/Xorg.0.log | grep \"X.Org X Server\" | awk {'print $4'}" Wait To xorg_version
  Shell ChkPrm.ChkExecDir("glxinfo") & "| grep \"GLX version:\" | sed -n '1p' | cut -d ':' -f 2" Wait To glx_version
  'Shell "echo $SHELL" Wait To TextBox67.Text
  
  Finfosys.GridView2.Columns.Count = 1
  Finfosys.GridView2.Rows.Count = 9
  
  Finfosys.GridView2[0, 0].Text = "Distro Vendor: " & SCREENFETCH["Distro"]
  Finfosys.GridView2[1, 0].Text = "Distro Release: " & SCREENFETCH["Distro_Release"]
  Finfosys.GridView2[2, 0].Text = "Desktop environment: " & SCREENFETCH["DE"]
  Finfosys.GridView2[3, 0].Text = "Window manager: " & SCREENFETCH["WM"]
  Finfosys.GridView2[4, 0].Text = "Window manager Theme: " & SCREENFETCH["WinTheme"]
  Finfosys.GridView2[5, 0].Text = "GTK+ 2 Theme: " & SCREENFETCH["GTK2Theme"]
  Finfosys.GridView2[6, 0].Text = "GTK+ 3 Theme: " & SCREENFETCH["GTK3Theme"]
  Finfosys.GridView2[7, 0].Text = "GTK Font: " & SCREENFETCH["GTKFont"]
  Finfosys.GridView2[8, 0].Text = "GTK Icons: " & SCREENFETCH["GTKIcons"]
  Finfosys.GridView2[8, 0].Text = "System SHELL: " & System.Shell
  Finfosys.GridView3.Columns.Count = 2
  Finfosys.GridView3.Rows.Count = 8
  Finfosys.GridView3.Columns.Width = 230
  Finfosys.GridView3[0, 0].Text = "GCC Version: " & Replace(gcc, "\n", "")
  Finfosys.GridView3[1, 0].Text = "Hostname: " & Replace(hostname, "\n", "")
  Finfosys.GridView3[2, 0].Text = "Arch: " & Replace(arch, "\n", "")
  Finfosys.GridView3[3, 0].Text = "Timezone: " & Replace(timezone, "\n", "")
  Finfosys.GridView3[4, 0].Text = "X.Org Version: " & Replace(xorg_version, "\n", "")
  Finfosys.GridView3[5, 0].Text = "GLX Version: " & Replace(glx_version, "\n", "")

  Distribution_Detect._inits
  
  Finfosys.GridView3[0, 1].Text = "Linux C Library: " & SCREENFETCH["LNXCLIB"]
  Finfosys.GridView3[1, 1].Text = "GNU Make Version: " & SCREENFETCH["GNUMAKE"]
  Finfosys.GridView3[2, 1].Text = "PPP: " & SCREENFETCH["PPP"]
  Finfosys.GridView3[3, 1].Text = "Dynamic linker (ldd): " & SCREENFETCH["DYNAMIC_LINKER"]
  Finfosys.GridView3[4, 1].Text = "Net-tools: " & SCREENFETCH["NETTOOLS"]
  Finfosys.GridView3[5, 1].Text = "Wireless-tools: " & SCREENFETCH["WIRELESS_TOOLS"]
  Finfosys.GridView3[6, 1].Text = Replace(SCREENFETCH["BINUTILS"], "\n", "")

  If default_display_manager = True Then
     Finfosys.GridView3[7, 0].Text = "Default Display Manager: " & Replace(File.Load("/etc/X11/default-display-manager"), "\n", "")
  Endif
  ' 
  ' Finfosys.TableView1.EditWith(Finfosys.TextBox37)
  ' Finfosys.TableView1.Columns.Count = 2
  ' Finfosys.TableView1.Rows.Count = 8
  ' Finfosys.TableView1[0, 0].Text = "Linux C Library: " & SCREENFETCH["LNXCLIB"]
  SCREENFETCH_P.Kill
  SCREENFETCH.Clear
End
