' Gambas module file

Public Sub _inits()
 Dim update_reccomended As String
 Dim update_driver As String
 If Exist("/var/log/dmesg") Then
 Shell "grep 'BIOS microcode update recommended' /var/log/dmesg" Wait To update_reccomended
 Shell "grep 'Microcode Update Driver:' /var/log/dmesg" Wait To update_driver
 Endif
 If update_reccomended Like "*BIOS microcode update recommended*" And update_driver Not Like "*Microcode Update Driver*" Then
 Finfosys.Label92.Text = "BIOS microcode update recommended !!!"
 Else
 Finfosys.Label92.Visible = False
 Debug "BIOS microcode update not recommended"
 Endif
End

