' Gambas module file

Public Report As Collection
Public DATA_RETURN As String
Public Sub refresh()
Report = [("0"): ("=======================================================" & Finfosys.ComboBox4.Text & "/" & Finfosys.ComboBox3.Text & "=================================================================="),
                               ("1"): (Finfosys.Label17.Text),
                               ("2"): (Finfosys.Label41.Text),
                               ("3"): (Finfosys.Label16.Text),
                               ("4"): (Finfosys.Label42.Text),
                               ("5"): (Finfosys.Label26.Text),
                               ("6"): (Finfosys.TextBox48.Text),
                               ("7"): (Finfosys.Label27.Text),
                               ("8"): (Finfosys.TextBox52.Text),
                               ("9"): (Finfosys.Label40.Text),
                               ("10"): (Finfosys.TextBox53.Text),
                               ("11"): (Finfosys.Label38.Text),
                               ("12"): (Finfosys.Label43.Text),
                               ("13"): (Finfosys.Label39.Text),
                               ("14"): (Finfosys.Label44.Text),
                               ("15"): (Finfosys.Label46.Text),
                               ("16"): (Finfosys.Label47.Text),
                               ("17"): (Finfosys.Label45.Text),
                               ("18"): (Finfosys.Label50.Text),
                               ("19"): (Finfosys.Label52.Text),
                               ("20"): (Finfosys.Label51.Text),
                               ("21"): (Finfosys.Label53.Text),
                               ("22"): (Finfosys.Label49.Text),
                               ("23"): (Finfosys.Label55.Text),
                               ("24"): (Finfosys.Label54.Text),
                               ("25"): (Finfosys.Label56.Text),
                               ("26"): (Finfosys.Label57.Text),
                               ("27"): (Finfosys.Label58.Text),
                               ("28"): (Finfosys.Label59.Text)]
End

Public Sub _inits()
 Dim All, All2, repcount As Integer
 DATA_RETURN = Null
 'refresh()

 For All2 = 1 To Finfosys.ComboBox4.Count
  
  refresh()
  If Finfosys.ComboBox3.Count = 0 Then
   For repcount = 0 To Report.Count
    FReport_Gen.ProgressBar1.Value = repcount / Report.Count
    DATA_RETURN = DATA_RETURN & "\n" & Report[repcount]
    Wait 0.01
   
   refresh()
   Next
  Endif
  
  For All = 1 To Finfosys.ComboBox3.Count
   refresh()
   
   For repcount = 0 To Report.Count
    FReport_Gen.ProgressBar1.Value = repcount / Report.Count
    DATA_RETURN = DATA_RETURN & "\n" & Report[repcount]
    Wait 0.01
   
   refresh()
   Next
   Finfosys.ComboBox3.Index = All
 Next
  
  refresh()
  
  Finfosys.ComboBox4.Index = All2
 
 Next
 
 Shell "echo '" & DATA_RETURN & "'>>" & FReport_Gen.ButtonBox1.Text & "" Wait

End
