' Gambas module file

Public DATA_RETURN As String
Public Report As Collection = [("0"): ("========================================================================================================================="),
                               ("1"): ("___________________Board___________________"),
                               ("2"): (Finfosys.TextLabel1.Text),
                               ("3"): (Finfosys.TextLabel2.Text),
                               ("4"): (Finfosys.TextLabel3.Text),
                               ("5"): (Finfosys.TextLabel4.Text),
                               ("6"): ("___________________Bios____________________"),
                               ("7"): (Finfosys.TextLabel5.Text),
                               ("8"): (Finfosys.TextLabel6.Text),
                               ("9"): (Finfosys.TextLabel14.Text),
                               ("10"): ("_________________Chassis__________________"),
                               ("11"): (Finfosys.TextLabel8.Text),
                               ("12"): (Finfosys.TextLabel9.Text),
                               ("13"): (Finfosys.TextLabel10.Text),
                               ("14"): (Finfosys.TextLabel11.Text),
                               ("15"): ("_________________Product__________________"), 
                               ("14"): (Finfosys.TextLabel12.Text),
                               ("14"): (Finfosys.TextLabel13.Text)]
Public Sub _inits()
Dim All As Integer
 DATA_RETURN = Null
  For All = 0 To Report.Count
  
   FReport_Gen.ProgressBar1.Value = All / Report.Count
   DATA_RETURN = DATA_RETURN & "\n" & Report[All]
  
  Wait 0.01
  
  Next
 
 Shell "echo '" & DATA_RETURN & "'>>" & FReport_Gen.ButtonBox1.Text & "" Wait 
End
