' Gambas module file

Public DATA_RETURN As String
Public Report As Collection = [("0"): ("========================================================================================================================="),
                               ("1"): ("________________Motherboard________________"),
                               ("2"): ("Manufacturer: " & Finfosys.TextBox23.Text),
                               ("3"): ("Model:        " & Finfosys.TextBox24.Text),
                               ("4"): ("___________________Bios____________________"),
                               ("5"): ("Manufacturer: " & Finfosys.TextBox25.Text),
                               ("6"): ("Date:         " & Finfosys.TextBox27.Text),
                               ("7"): ("Version:      " & Finfosys.TextBox26.Text)]
Public Sub _inits()
Dim All, All2 As Integer
 DATA_RETURN = Null
  For All = 0 To Report.Count
  
   FReport_Gen.ProgressBar1.Value = All / Report.Count
   DATA_RETURN = DATA_RETURN & "\n" & Report[All]
  
  Wait 0.01
  
  Next
 
 Shell "echo '" & DATA_RETURN & "'>>" & FReport_Gen.ButtonBox1.Text & "" Wait 
End
