' Gambas module file

Public DATA_RETURN As String
Public Report As Collection = [("0"): ("========================================================================================================================="),
                               ("1"): (Finfosys.Label4.Text),
                               ("2"): (Finfosys.Label135.Text),
                               ("3"): (Finfosys.Label136.Text),
                               ("4"): (Finfosys.Label137.Text),
                               ("5"): (Finfosys.Label138.Text),
                               ("6"): (Finfosys.Label139.Text),
                               ("7"): (Finfosys.Label140.Text),
                               ("8"): (Finfosys.Label141.Text),
                               ("9"): (Finfosys.Label142.Text),
                               ("10"): (Finfosys.Label143.Text),
                               ("11"): (Finfosys.Label144.Text),
                               ("12"): (Finfosys.Label145.Text),
                               ("13"): (Finfosys.Label37.Text),
                               ("14"): (Finfosys.Label60.Text),
                               ("15"): (Finfosys.Label61.Text),
                               ("16"): (Finfosys.Label62.Text),
                               ("17"): (Finfosys.Label63.Text),
                               ("18"): (Finfosys.Label147.Text),
                               ("19"): (Finfosys.Label148.Text)]
Public Sub _inits()
Dim All As Integer
 DATA_RETURN = Null
  For All = 0 To Report.Count
  
   FReport_Gen.ProgressBar1.Value = All / Report.Count
   DATA_RETURN = DATA_RETURN & "\n" & Report[All]
  
  Wait 0.01
  
  Next
 
 Shell "echo '" & DATA_RETURN & "'>>" & FReport_Gen.ButtonBox1.Text & "" Wait 
End