#!/bin/bash
#  detectwm.sh
#  detect and output the name of the Window Manager, if present
#  only meant to be run on Linux/*BSD
#  Original Author: Brett Bohnenkamper (KittyKatt) in screenfetch-dev
#  Modified to stand alone by William Woodruff (woodrufw) in screenfetch-c

wmnames=( fluxbox openbox blackbox xfwm4 metacity kwin icewm pekwm fvwm dwm awesome wmaker stumpwm musca i3 xmonad ratpoison scrotwm spectrwm wmfs wmii beryl subtle e16 enlightenment sawfish emerald monsterwm dminiwm compiz Finder herbstluftwm )
WM="Unknown"
if [[ -n ${DISPLAY} ]]; then
	if type -p xprop >/dev/null 2>&1; then
		WM=$(xprop -root _NET_SUPPORTING_WM_CHECK)
		if [[ "$WM" =~ 'Unknown' ]]; then
			WM="Unknown"
		elif [[ "$WM" =~ 'Unknown' ]]; then
			WM="Unknown"
		elif [[ "$WM" =~ '[Ii]nvalid window id format' ]]; then
			WM="Unknown"
		elif [[ "$WM" =~ "no such" ]]; then
			WM="Unknown"
		else
			WM=${WM//* }
			WM=$(xprop -id ${WM} 8s _NET_WM_NAME)
			WM=$(echo $(WM=${WM//*= }; echo ${WM//\"}))
		fi
	fi
	if [[ ${WM} == "Unknown" ]]; then
		for each in $wmnames; do
			PID="$(pgrep -U ${UID} $each)"
			if [ "$PID" ]; then
				case $each in
					'awesome') WM="Awesome";;
					'beryl') WM="Beryl";;
					'blackbox') WM="Blackbox";;
					'cinnamon') WM="Cinnamon";;
					'compiz') WM="Compiz";;
					'dminiwm') WM="dminiwm";;
					'dwm') WM="DWM";;
					'e16') WM="E16";;
					'emerald') WM="Emerald";;
					'enlightenment') WM="E17";;
					'fluxbox') WM="FluxBox";;
					'fvwm') WM="FVWM";;
					'herbstluftwm') WM="herbstluftwm";;
					'icewm') WM="IceWM";;
					'kwin') WM="KWin";;
					'metacity') WM="Metacity";;
					'monsterwm') WM="monsterwm";;
					'musca') WM="Musca";;
					'openbox') WM="OpenBox";;
					'pekwm') WM="PekWM";;
					'ratpoison') WM="Ratpoison";;
					'sawfish') WM="Sawfish";;
					'scrotwm') WM="ScrotWM";;
					'spectrwm') WM="SpectrWM";;
					'stumpwm') WM="StumpWM";;
					'subtle') WM="subtle";;
					'wmaker') WM="WindowMaker";;
					'wmfs') WM="WMFS";;
					'wmii') WM="wmii";;
					'xfwm4') WM="Xfwm4";;
					'xmonad') WM="XMonad";;
					'i3') WM="i3";;
				esac
			fi
			if [[ ${WM} != "Unknown" ]]; then
				break 1
			fi
		done
	else
		if [[ ${BASH_VERSINFO[0]} -ge 4 ]]; then
			if [[ ${BASH_VERSINFO[0]} -eq 4 && ${BASH_VERSINFO[1]} -gt 1 ]] || [[ ${BASH_VERSINFO[0]} -gt 4 ]]; then
				WM=${WM,,}
			else
				WM="$(tr '[:upper:]' '[:lower:]' <<< ${WM})"
			fi
		else
			WM="$(tr '[:upper:]' '[:lower:]' <<< ${WM})"
		fi
		case ${WM} in
			'awesome') WM="Awesome";;
			'beryl') WM="Beryl";;
			'blackbox') WM="Blackbox";;
			'cinnamon') WM="Cinnamon";;
			'compiz') WM="Compiz";;
			'dminiwm') WM="dminiwm";;
			'dwm') WM="DWM";;
			'e16') WM="E16";;
			'emerald') WM="Emerald";;
			'enlightenment') WM="E17";;
			'fluxbox') WM="FluxBox";;
			'fvwm') WM="FVWM";;
			'herbstluftwm') WM="herbstluftwm";;
			'icewm') WM="IceWM";;
			'kwin') WM="KWin";;
			'metacity') WM="Metacity";;
			'monsterwm') WM="monsterwm";;
			'musca') WM="Musca";;
			'openbox') WM="OpenBox";;
			'pekwm') WM="PekWM";;
			'ratpoison') WM="Ratpoison";;
			'sawfish') WM="Sawfish";;
			'scrotwm') WM="ScrotWM";;
			'spectrwm') WM="SpectrWM";;
			'stumpwm') WM="StumpWM";;
			'subtle') WM="subtle";;
			'wmaker') WM="WindowMaker";;
			'wmfs') WM="WMFS";;
			'wmii') WM="wmii";;
			'xfwm4') WM="Xfwm4";;
			'xmonad') WM="XMonad";;
			'i3') WM="i3";;
		esac
	fi
fi
echo $WM > ~/.i-nex/WM.conf