#!/bin/bash
#  detectde.sh
#  detect and output the name of the Desktop Environment, if present
#  only meant to be run on Linux/*BSD
#  Original Author: Brett Bohnenkamper (KittyKatt) in screenfetch-dev
#  Modified to stand alone by William Woodruff (woodrufw) in screenfetch-c


DE="Unknown"
if [[ -n ${DISPLAY} ]]; then
	if type -p xprop >/dev/null 2>&1;then
		xprop_root="$(xprop -root 2>/dev/null)"
		if [[ -n ${xprop_root} ]]; then
			DE=$(echo "${xprop_root}" | awk 'BEGIN {
				de = "Unknown"
			}
			{
				if ($1 ~ /^_DT_SAVE_MODE/) {
					de = $NF
					gsub(/\"/,"",de)
					de = toupper(de)
					exit
				}
				else if ($1 ~/^KDE_SESSION_VERSION/) {
					de = "KDE"$NF
					exit
				}
				else if ($1 ~ /^_MARCO/) {
					de = "MATE"
					exit
				}
				else if ($1 ~ /^_MUFFIN/) {
					de = "Cinnamon"
					exit
				}
				else if ($0 ~ /"xfce4"/) {
					de = "XFCE4"
					exit
				}
				else if ($0 ~ /"xfce5"/) {
					de = "XFCE5"
					exit
				}
			} END {
				print de
			}')
		fi
	fi
	if [[ ${DE} == "Unknown" ]]; then
		if [[ -n ${GNOME_DESKTOP_SESSION_ID} ]]; then
			DE="Gnome"
			if type -p xprop >/dev/null 2>&1; then
				if xprop -name "unity-launcher" >/dev/null 2>&1; then
					DE="Unity"
				elif xprop -name "launcher" >/dev/null 2>&1 &&
					xprop -name "panel" >/dev/null 2>&1; then
					DE="Unity"
				fi
			fi
		elif [[ -n ${MATE_DESKTOP_SESSION_ID} ]]; then
			DE="MATE"
		elif [[ -n ${KDE_SESSION_VERSION} ]]; then
			if [[ ${KDE_SESSION_VERSION} == '5' ]]; then
				DE="KDE5"
			elif [[ ${KDE_SESSION_VERSION} == '4' ]]; then
				DE="KDE4"
			fi
		elif [[ -n ${KDE_FULL_SESSION} ]]; then
			if [[ ${KDE_FULL_SESSION} == 'true' ]]; then
				DE="KDE"
				DEver_data=$( kded4 --version 2>/dev/null )
				DEver=$( grep -si '^KDE:' <<< "$DEver_data" | awk '{print $2}' )
			fi
		fi
	fi
	if [[ ${DE} != "Unknown" ]]; then
		if [[ ${DE} == "Cinnamon" ]]; then
			if type -p >/dev/null 2>&1; then
				DEver=$(cinnamon --version)
				DE="${DE} ${DEver//* }"
			fi
		elif [[ ${DE} == "Gnome" || ${DE} == "GNOME" ]]; then
			if type -p gnome-session-properties >/dev/null 2>&1; then
				DEver=$(gnome-session-properties --version)
				DE="${DE} ${DEver//* }"
			elif type -p gnome-session >/dev/null 2>&1; then
				DEver=$(gnome-session --version)
				DE="${DE} ${DEver//* }"
			fi
		elif [[ ${DE} == "KDE4" || ${DE} == "KDE5" ]]; then
			if type -p kded${DE#KDE} >/dev/null 2>&1; then
				DEver=$(kded${DE#KDE} --version)
				for l in $(echo "${DEver// /_}"); do
					if [[ ${l//:*} == "KDE_Development_Platform" ]]; then
						DEver=${l//*:_}
						DE="KDE ${DEver//_*}"
					fi;
				done
			fi
		elif [[ ${DE} == "MATE" ]]; then
			if type -p mate-session >/dev/null 2>&1; then
				DEver=$(mate-session --version)
				DE="${DE} ${DEver//* }"
			fi
		elif [[ ${DE} == "Unity" ]]; then
			if type -p unity >/dev/null 2>&1; then
				DEver=$(unity --version)
				DE="${DE} ${DEver//* }"
			fi
		fi
	fi
	if [[ "${DE}" == "Unknown" ]]; then
		if pgrep -U ${UID} lxsession >/dev/null 2>&1; then
			DE="LXDE"
			if type -p lxpanel >/dev/null 2>&1; then
				DEver=$(lxpanel -v)
				DE="${DE} $DEver"
			fi
		elif pgrep -U ${UID} razor-session >/dev/null 2>&1; then
			DE="RazorQt"
		fi
	fi

	printf $DE
fi
echo $DE > ~/.i-nex/DE.conf