' Gambas module file

' Copyright(C) 2011-2014, Michał Głowienka aka eloaders <eloaders@linux.pl>
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program. If not, see <http://www.gnu.org/licenses/>.

Function ChkExec(executable As String) As Boolean

  Dim i As Integer

  i = InStr(executable, " ")
  If i Then executable = Left(executable, i - 1)

  Shell "which " & executable & " >/dev/null 2>&1" Wait

  If Process.LastValue Then Return False
  Return True

End

Function ChkExecDir(executable As String) As String

  Dim installdir As String
  Shell "which " & executable & "" Wait To installdir
  installdir = Replace(Replace(installdir, " ", ""), "\n", "")
  Return installdir
End
